version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/samples/nodejs/auto-signin"
      - "/samples/nodejs/azure-ai-streaming"
      - "/samples/nodejs/cards"
      - "/samples/nodejs/copilotstudio-client"
      - "/samples/nodejs/copilot-sdk"
      - "/samples/nodejs/copilotstudio-skill"
      - "/samples/nodejs/copilotstudio-webchat-react"
      - "/samples/nodejs/langchain-multiturn"
      - "/samples/nodejs/multi-turn-prompt"
      - "/samples/nodejs/named-pipe-agent"
      - "/samples/nodejs/obo-authorization"
      - "/samples/nodejs/otel"
      - "/samples/nodejs/quickstart"
    schedule:
      interval: "monthly"
    groups:
      npm-all:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directories:
      - "/samples/python/auto-signin"
      - "/samples/python/azureai-streaming"
      - "/samples/python/cards"
      - "/samples/python/copilotstudio-client"
      - "/samples/python/copilot-sdk"
      - "/samples/python/copilotstudio-skill"
      - "/samples/python/obo-authorization"
      - "/samples/python/otel"
      - "/samples/python/quickstart"
      - "/samples/python/semantic-kernel-multiturn"
    schedule:
      interval: "monthly"
    groups:
      pip-all:
        patterns:
          - "*"

  - package-ecosystem: "nuget"
    directories:
      - "/samples/dotnet/Agent Framework"
      - "/samples/dotnet/auto-signin"
      - "/samples/dotnet/azure-ai-streaming"
      - "/samples/dotnet/copilotstudio-client"
      - "/samples/dotnet/copilot-sdk"
      - "/samples/dotnet/copilotstudio-skill"
      - "/samples/dotnet/genesys-handoff"
      - "/samples/dotnet/multiagent"
      - "/samples/dotnet/named-pipe-agent"
      - "/samples/dotnet/obo-authorization"
      - "/samples/dotnet/otel"
      - "/samples/dotnet/proactive"
      - "/samples/dotnet/quickstart"
      - "/samples/dotnet/retrieval-agent"
      - "/samples/dotnet/semantic-kernel-multiturn"
      - "/samples/dotnet/slackagent"
    schedule:
      interval: "monthly"
    groups:
      nuget-all:
        patterns:
          - "*"
