// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

using Microsoft.Agents.Builder;
using Microsoft.Agents.Builder.App;
using Microsoft.Agents.Builder.State;
using Microsoft.Agents.Core.Models;
using Microsoft.Agents.Extensions.MSTeams;
using Microsoft.Agents.Extensions.MSTeams.App;
using System.Collections.Generic;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;

namespace BotAiMessages;

[TeamsExtension]
public partial class BotAiMessagesAgent(AgentApplicationOptions options) : AgentApplication(options)
{
    [TeamsMessageRoute]
    public async Task OnMessageAsync(
        ITeamsTurnContext turnContext,
        ITurnState turnState,
        CancellationToken cancellationToken)
    {
        string text = turnContext.Activity.Text?.Trim().ToLowerInvariant() ?? string.Empty;

        if (text.Contains("label"))
        {
            await SendAiLabelAsync(turnContext, cancellationToken);
        }
        else if (text.Contains("feedback"))
        {
            await SendFeedbackButtonsAsync(turnContext, cancellationToken);
        }
        else if (text.Contains("sensitivity"))
        {
            await SendSensitivityLabelAsync(turnContext, cancellationToken);
        }
        else if (text.Contains("citation"))
        {
            await SendCitationsAsync(turnContext, cancellationToken);
        }
        else
        {
            await turnContext.SendActivityAsync(
                MessageFactory.Text("Welcome to the AI bot! Try sending messages with keywords like 'label', 'sensitivity', 'feedback', or 'citation' to see different AI features."),
                cancellationToken);
        }
    }

    [TeamsFeedbackLoopRoute]
    public async Task OnFeedbackAsync(
        ITeamsTurnContext turnContext,
        ITurnState turnState,
        FeedbackData feedbackData,
        CancellationToken cancellationToken)
    {
        string reaction = "No reaction";
        string feedbackText = "No feedback was provided.";

        if (feedbackData.ActionValue is not null)
        {
            string json = JsonSerializer.Serialize(feedbackData.ActionValue);
            using JsonDocument document = JsonDocument.Parse(json);
            JsonElement root = document.RootElement;

            if (root.TryGetProperty("reaction", out JsonElement reactionProperty))
            {
                reaction = reactionProperty.GetString() ?? "No reaction";
            }

            if (root.TryGetProperty("feedback", out JsonElement feedbackProperty))
            {
                string? feedbackJson = feedbackProperty.GetString();
                if (!string.IsNullOrEmpty(feedbackJson))
                {
                    using JsonDocument feedbackDocument = JsonDocument.Parse(feedbackJson);
                    if (feedbackDocument.RootElement.TryGetProperty("feedbackText", out JsonElement feedbackTextProperty))
                    {
                        feedbackText = feedbackTextProperty.GetString() ?? "No feedback was provided.";
                    }
                }
            }
        }

        await turnContext.SendActivityAsync(
            MessageFactory.Text($"Provided reaction: {reaction}<br> Feedback: {feedbackText}"),
            cancellationToken);
    }

    private static Task SendAiLabelAsync(ITeamsTurnContext turnContext, CancellationToken cancellationToken)
    {
        IActivity activity = Activity.CreateMessageActivity();
        activity.Text = "Hi, this message is generated by AI";
        activity.Entities =
        [
            new AIEntity
            {
                AdditionalType = [AIEntity.AdditionalTypeAIGeneratedContent]
            }
        ];

        return turnContext.SendActivityAsync(activity, cancellationToken);
    }

    private static Task SendFeedbackButtonsAsync(ITeamsTurnContext turnContext, CancellationToken cancellationToken)
    {
        IActivity activity = Activity.CreateMessageActivity();
        activity.Text = "This is an example of a feedback button - this helps to provide feedback for a message";
        activity.TeamsEnableFeedbackLoop();

        return turnContext.SendActivityAsync(activity, cancellationToken);
    }

    private static Task SendSensitivityLabelAsync(ITeamsTurnContext turnContext, CancellationToken cancellationToken)
    {
        IActivity activity = Activity.CreateMessageActivity();
        activity.Text = "This is an example of a sensitivity label that help users identify the confidentiality of a message";
        activity.Entities =
        [
            new AIEntity
            {
                UsageInfo = new SensitivityUsageInfo
                {
                    Name = "Confidential \\ Contoso FTE",
                    Description = "Please be mindful of sharing outside of your team"
                }
            }
        ];

        return turnContext.SendActivityAsync(activity, cancellationToken);
    }

    private static Task SendCitationsAsync(ITeamsTurnContext turnContext, CancellationToken cancellationToken)
    {
        IActivity activity = Activity.CreateMessageActivity();
        activity.Text = "Hey I'm a friendly AI bot. This message is generated through AI [1]";
        activity.Entities =
        [
            new AIEntity
            {
                Citation =
                [
                    new ClientCitation(
                        1,
                        "AI messages bot",
                        "Excerpt description",
                        string.Empty,
                        new List<string> { "keyword 1", "keyword 2", "keyword 3" },
                        "https://example.com/claim-1",
                        ClientCitationIconName.MicrosoftWord)
                ]
            }
        ];

        return turnContext.SendActivityAsync(activity, cancellationToken);
    }
}
