<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.18.*" />
    <PackageReference Include="Microsoft.Agents.Authentication.Msal" Version="1.7.*" />
    <PackageReference Include="Microsoft.Agents.Extensions.MSTeams" Version="1.7.*" />
    <PackageReference Include="Microsoft.Agents.Hosting.AspNetCore" Version="1.7.*" />
    <PackageReference Include="Microsoft.Graph" Version="5.103.*" />
    <PackageReference Include="Microsoft.Teams.Cards" Version="2.0.*" />
  </ItemGroup>

</Project>
